version: 2.0

build_and_test: &build_and_test_steps
  - checkout
  # Do not use `sudo pip`
  # pipx is already installed but `pipx list` is empty
  - run: python --version ; pip --version ; pipx --version ; pwd ; ls -l
  - run: pip install pytest -r requirements.txt
  - run: pip install --editable .
  - run: pytest


jobs:
  StyleCheck:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run: python --version ; pip --version ; pwd ; ls -l
      - run: pip install black codespell flake8 ruff
      - run: codespell -L queenland,uint
      # stop the build if there are Python syntax errors or undefined names
      - run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      # exit-zero treats all errors as warnings.  The GitHub editor is 127 chars wide
      - run: flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - run: black . --check


  Python3:
    docker:
      - image: cimg/python:3.11
    steps: *build_and_test_steps


workflows:
  version: 2
  build:
    jobs:
      - StyleCheck
      - Python3
